model:
  bottleneck_size: 10

training:
  epochs: 500
  batch_size: 1
  patience: 50
  model_name: lstm_coae_3repeats
  tuner_name: lstm_coae_tuner_3repeats
  step_size: 50
  gamma: 0.5

data:
  directory: data/coeffs/
  suffix: _density_data.h5
  test_years:
  - 1997
  - 1998
  - 1999
  - 2001
  training_years:
  - 1996
  - 1997
  - 1998
  - 1999
  - 2000
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  validation_years:
  - 1996
  - 2000
  # - 1997
  # - 1998
  # - 1999
  # - 2001
  nm: 10
  notS: 3
  noI: 6
  batch_size: 1